version: "3"
services:
  plex:
    container_name: plexIobroker
    image: iobrokerplexwebhook:0.0.1
    restart: always
    ports:
      - "5000:5000/tcp"
    environment:
      IOBROKER_STATE_URL: "http://192.168.178.145:8087/set/0_userdata.0.plexEvent?value="
