name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: docker buildx build . --platform linux/arm/v7 --file Dockerfile --tag my-image-name:$(date +%s)
